### ISSUE TITLE
5.2 Completely stops my site

### ISSUE THREAD

**Issue by phillipmadsen** [amsgames/laravel-shop#37]
here is the error code:

PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /vendor/laravel/framework/src/Illuminate/Container/Container.php:738
Stack trace:
#0 /vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionClass->__construct('log')
#1 /vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('log', Array)
#2 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('log', Array)
#3 /vendor/laravel/framework/src/Illuminate/Container/Container.php(853): Illuminate\Foundation\Application->make('log')
#4 /vendor/laravel/framework/src/Illuminate/Container/Container.php(808): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /vendor/laravel/framework/src/Illumina in /vendor/laravel/framework/src/Illuminate/Container/Container.php on line 738

**Comment by phillipmadsen** [comment]
looks like its being caused by something int  Amsgames\LaravelShop\LaravelShopFacade::class,

**Comment by amostajo** [comment]
Pull request solved this for 5.2
